export const FETCH_SUCCESS = 'FETCH_SUCCESS';
export const FETCH_START = 'FETCH_START';
export const FETCH_FAILED = 'FETCH_FAILED';
export const FETCH_SINGLE_BLOG_SUCCESS = 'FETCH_SINGLE_BLOG_SUCCESS';
export const FETCH_SINGLE_FAILED = 'FETCH_SINGLE_FAILED';
export const DELETE_SINGLE_BLOG = 'DELETE_SINGLE_BLOG'